<?php
/** Neurocoaching page. @package Neurocoaching */
get_header();
?>
<section class="nc-hero nc-hero--neuro" aria-labelledby="neuro-title"><div class="nc-container nc-hero__grid"><div><p class="nc-eyebrow">Neurointegration coaching</p><h1 class="nc-title" id="neuro-title">Burned out, overwhelmed, or know something needs to change?</h1><p class="nc-copy nc-hero__meta"><?php echo esc_html( neurocoaching_mod( 'neuro_intro', 'A brain-aware coaching space for finding steadier ways to work, decide and live.' ) ); ?></p></div><div class="nc-hero__placeholder" role="img" aria-label="Neurocoaching client photo placeholder — awaiting source asset"><span class="nc-placeholder-label">Photo placeholder — awaiting client asset</span></div></div></section>

<section class="nc-section" aria-labelledby="neuro-education-title"><div class="nc-container nc-split"><div><p class="nc-eyebrow">Background</p><h2 class="nc-heading" id="neuro-education-title">Education &amp; Experience</h2><p class="nc-copy">A coaching approach informed by neurobiology, patterns of attention, emotional regulation and lived change.</p></div><ul class="nc-facts"><li><strong>01</strong><span>Neurointegration and coaching practice</span></li><li><strong>02</strong><span>Support through burnout, overwhelm and transition</span></li><li><strong>03</strong><span>Reflection grounded in everyday experiments</span></li></ul></div></section>

<section class="nc-section nc-section--forest" aria-labelledby="neuro-brain-title"><div class="nc-container nc-split"><p class="nc-eyebrow">A different way in</p><div><h2 class="nc-heading" id="neuro-brain-title">Your brain is not a problem to solve.</h2><p class="nc-copy">We notice the protective patterns beneath the struggle, create enough safety for new possibilities, and practise choices that can hold up outside the session.</p></div></div></section>

<section class="nc-section nc-section--cream" aria-labelledby="neuro-services-title"><div class="nc-container"><p class="nc-eyebrow">Ways to work together</p><h2 class="nc-heading" id="neuro-services-title">Services | Neurointegration</h2><div class="nc-cards">
	<article class="nc-card"><span class="nc-card__number">01</span><h3>One-to-one coaching</h3><p>A focused space to understand patterns, regulate pressure and move toward change.</p></article>
	<article class="nc-card"><span class="nc-card__number">02</span><h3>Burnout support</h3><p>Rebuild capacity and make decisions without returning to the habits that depleted you.</p></article>
	<article class="nc-card"><span class="nc-card__number">03</span><h3>Transition work</h3><p>Stay connected to yourself while identity, work or circumstances are shifting.</p></article>
</div></div></section>

<section class="nc-section" aria-labelledby="neuro-story-title"><div class="nc-container nc-split"><?php neurocoaching_placeholder( 'Personal story photo placeholder — awaiting source asset' ); ?><div><p class="nc-eyebrow">Why this work</p><h2 class="nc-heading" id="neuro-story-title">My personal story</h2><p class="nc-copy">This section is reserved for Ksenia’s approved personal story. Final copy and photography are intentionally not invented in this first staging build.</p></div></div></section>

<section class="nc-section nc-section--sage" aria-labelledby="neuro-method-title"><div class="nc-container"><p class="nc-eyebrow">The approach</p><h2 class="nc-heading" id="neuro-method-title">A method built around awareness, regulation and action.</h2><div class="nc-cards"><article class="nc-card"><span class="nc-card__number">Notice</span><h3>See the pattern</h3><p>Name what happens without judgement or premature fixing.</p></article><article class="nc-card"><span class="nc-card__number">Integrate</span><h3>Create capacity</h3><p>Work with mind and body so new responses become possible.</p></article><article class="nc-card"><span class="nc-card__number">Practise</span><h3>Make it real</h3><p>Test small, meaningful changes in the context of daily life.</p></article></div></div></section>

<section class="nc-section" aria-labelledby="neuro-fit-title"><div class="nc-container nc-split"><div><p class="nc-eyebrow">Is this for you?</p><h2 class="nc-heading" id="neuro-fit-title">Change does not have to begin with certainty.</h2></div><ul class="nc-facts"><li><strong>✓</strong><span>You are tired of overriding yourself to keep going.</span></li><li><strong>✓</strong><span>You understand the problem intellectually, but the pattern stays.</span></li><li><strong>✓</strong><span>You want a gentler approach that remains practical.</span></li></ul></div></section>

<section class="nc-section nc-section--forest" aria-labelledby="neuro-reviews-title"><div class="nc-container"><p class="nc-eyebrow">Reviews</p><h2 class="screen-reader-text" id="neuro-reviews-title">Neurocoaching reviews</h2><blockquote class="nc-quote">“I left with more space, less self-judgement and one next step that genuinely felt possible.”<footer>Anonymous client · staging testimonial placeholder</footer></blockquote></div></section>

<section class="nc-section" aria-labelledby="neuro-life-title"><div class="nc-container"><p class="nc-eyebrow">Beyond the session</p><h2 class="nc-heading" id="neuro-life-title">In real life</h2><div class="nc-gallery"><?php neurocoaching_placeholder( 'Real-life photo placeholder 1 — awaiting source asset' ); neurocoaching_placeholder( 'Real-life photo placeholder 2 — awaiting source asset' ); neurocoaching_placeholder( 'Real-life photo placeholder 3 — awaiting source asset' ); ?></div></div></section>

<section class="nc-section nc-section--cream nc-cta" aria-labelledby="neuro-cta-title"><div class="nc-container"><p class="nc-eyebrow">Start here</p><h2 class="nc-heading" id="neuro-cta-title">You can begin before you have it all figured out.</h2><p class="nc-copy">Bring what feels tangled. We will find a steady first thread.</p><p><a class="nc-button" href="<?php echo esc_url( neurocoaching_mod( 'contact_url', 'https://www.linkedin.com/' ) ); ?>">Connect on LinkedIn</a></p></div></section>
<?php neurocoaching_faqs( 'neuro' ); ?>
<?php get_footer(); ?>
